name: pir
dependencies:
  - python=3.11
  - pylint  # linting
  - mypy  # linting
  - types-passlib  # TODO: where to put lib stubs
  - pip:
      - -r app/requirements.txt
      - -r migrations/requirements.txt
      - -r tests/requirements.txt
