name: myservice

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-main}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "5432:5432"

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.app
    image: myapp
    depends_on: [postgres]
    ports:
      - "80:80"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://admin:admin@postgres:5432/main}

  test:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
    depends_on: [app]
    volumes:
      - ../app:/app
      - ../tests:/tests
    command: ["pytest", "tests/"]