name: App Docker Image

on:
  push:
    branches:
    - master

jobs:

  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: environment
      run: pwd && ls -la && docker version && docker compose version

    - name: build docker images
      run: docker compose build
    
    - name: start postgres
      run: docker compose up -d postgres

    - name: run migrations
      run: |
        sleep 5 && \
        docker compose run --rm migrations alembic upgrade head

    - name: check migrations
      run: docker compose run --rm migrations alembic check

    - name: run functional tests
      run: docker compose run --rm tests pytest tests/functional

    - name: reset database and app
      run: |
        docker compose down && \
        docker compose up -d postgres app && \
        sleep 5 && \
        docker compose run --rm migrations alembic upgrade head

    - name: run concurrency test
      run: docker compose run --rm tests python tests/e2e/concurrency.py
