name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: See environment
      run: pwd && ls -la
    - name: What docker do I have here?
      run: docker--version && docker-compose --version
    - name: Trying to build the testing stack
      run: docker-compose -f docker/docker-compose-test.yml build
    - name: Running the test
      run: docker-compose -f docker/docker-compose-test.yml up --exit-code-from test
    
